# Dependencies
markdown:         rdiscount
highlighter:      pygments
 
# Permalinks
permalink:        /:categories/:title
 
# Server
destination:      _site
host:             localhost
port:             9001
url:       		  http://nicos-mbp.local:5757/
baseurl:          /
encoding:         UTF-8

# LOCAL-DEV BRANCH
client_cdn:       	
site_cdn:
start_comment: <!--
end_comment: -->

# CDN-PRODUCTION BRANCH
# client_cdn: 		http://cdn.studioncreations.com/client
# site_cdn:         http://cdn.studioncreations.com
# start_comment: 
# end_comment: 